/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ShellAuditRouteImport } from './routes/_shell.audit'
import { Route as ShellDashboardRouteImport } from './routes/_shell.dashboard'
import { Route as ShellFulfillmentRouteImport } from './routes/_shell.fulfillment'
import { Route as ShellInventoryRouteImport } from './routes/_shell.inventory'
import { Route as ShellProductsRouteImport } from './routes/_shell.products'
import { Route as ShellSellersRouteImport } from './routes/_shell.sellers'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'
import { Route as ShellUsersRouteImport } from './routes/_shell.users'
import { Route as ShellOrdersIndexRouteImport } from './routes/_shell.orders.index'
import { Route as ShellOrdersOrderIdRouteImport } from './routes/_shell.orders.$orderId'
import { Route as ShellOrdersNewRouteImport } from './routes/_shell.orders.new'
import { Route as ShellReceivingIndexRouteImport } from './routes/_shell.receiving.index'
import { Route as ShellReceivingReceiptIdRouteImport } from './routes/_shell.receiving.$receiptId'
import { Route as ShellReceivingNewRouteImport } from './routes/_shell.receiving.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellAuditRoute = ShellAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellFulfillmentRoute = ShellFulfillmentRouteImport.update({
  id: '/fulfillment',
  path: '/fulfillment',
  getParentRoute: () => ShellRoute,
} as any)
const ShellInventoryRoute = ShellInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProductsRoute = ShellProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSellersRoute = ShellSellersRouteImport.update({
  id: '/sellers',
  path: '/sellers',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellUsersRoute = ShellUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ShellRoute,
} as any)
const ShellOrdersIndexRoute = ShellOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellOrdersOrderIdRoute = ShellOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => ShellRoute,
} as any)
const ShellOrdersNewRoute = ShellOrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => ShellRoute,
} as any)
const ShellReceivingIndexRoute = ShellReceivingIndexRouteImport.update({
  id: '/receiving/',
  path: '/receiving/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellReceivingReceiptIdRoute = ShellReceivingReceiptIdRouteImport.update({
  id: '/receiving/$receiptId',
  path: '/receiving/$receiptId',
  getParentRoute: () => ShellRoute,
} as any)
const ShellReceivingNewRoute = ShellReceivingNewRouteImport.update({
  id: '/receiving/new',
  path: '/receiving/new',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/audit': typeof ShellAuditRoute
  '/dashboard': typeof ShellDashboardRoute
  '/fulfillment': typeof ShellFulfillmentRoute
  '/inventory': typeof ShellInventoryRoute
  '/products': typeof ShellProductsRoute
  '/sellers': typeof ShellSellersRoute
  '/settings': typeof ShellSettingsRoute
  '/users': typeof ShellUsersRoute
  '/orders/$orderId': typeof ShellOrdersOrderIdRoute
  '/orders/new': typeof ShellOrdersNewRoute
  '/receiving/$receiptId': typeof ShellReceivingReceiptIdRoute
  '/receiving/new': typeof ShellReceivingNewRoute
  '/orders/': typeof ShellOrdersIndexRoute
  '/receiving/': typeof ShellReceivingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/audit': typeof ShellAuditRoute
  '/dashboard': typeof ShellDashboardRoute
  '/fulfillment': typeof ShellFulfillmentRoute
  '/inventory': typeof ShellInventoryRoute
  '/products': typeof ShellProductsRoute
  '/sellers': typeof ShellSellersRoute
  '/settings': typeof ShellSettingsRoute
  '/users': typeof ShellUsersRoute
  '/orders/$orderId': typeof ShellOrdersOrderIdRoute
  '/orders/new': typeof ShellOrdersNewRoute
  '/receiving/$receiptId': typeof ShellReceivingReceiptIdRoute
  '/receiving/new': typeof ShellReceivingNewRoute
  '/orders': typeof ShellOrdersIndexRoute
  '/receiving': typeof ShellReceivingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_shell/audit': typeof ShellAuditRoute
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/fulfillment': typeof ShellFulfillmentRoute
  '/_shell/inventory': typeof ShellInventoryRoute
  '/_shell/products': typeof ShellProductsRoute
  '/_shell/sellers': typeof ShellSellersRoute
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/users': typeof ShellUsersRoute
  '/_shell/orders/$orderId': typeof ShellOrdersOrderIdRoute
  '/_shell/orders/new': typeof ShellOrdersNewRoute
  '/_shell/receiving/$receiptId': typeof ShellReceivingReceiptIdRoute
  '/_shell/receiving/new': typeof ShellReceivingNewRoute
  '/_shell/orders/': typeof ShellOrdersIndexRoute
  '/_shell/receiving/': typeof ShellReceivingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/audit'
    | '/dashboard'
    | '/fulfillment'
    | '/inventory'
    | '/products'
    | '/sellers'
    | '/settings'
    | '/users'
    | '/orders/$orderId'
    | '/orders/new'
    | '/receiving/$receiptId'
    | '/receiving/new'
    | '/orders/'
    | '/receiving/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/audit'
    | '/dashboard'
    | '/fulfillment'
    | '/inventory'
    | '/products'
    | '/sellers'
    | '/settings'
    | '/users'
    | '/orders/$orderId'
    | '/orders/new'
    | '/receiving/$receiptId'
    | '/receiving/new'
    | '/orders'
    | '/receiving'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/login'
    | '/signup'
    | '/_shell/audit'
    | '/_shell/dashboard'
    | '/_shell/fulfillment'
    | '/_shell/inventory'
    | '/_shell/products'
    | '/_shell/sellers'
    | '/_shell/settings'
    | '/_shell/users'
    | '/_shell/orders/$orderId'
    | '/_shell/orders/new'
    | '/_shell/receiving/$receiptId'
    | '/_shell/receiving/new'
    | '/_shell/orders/'
    | '/_shell/receiving/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/audit': {
      id: '/_shell/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof ShellAuditRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/fulfillment': {
      id: '/_shell/fulfillment'
      path: '/fulfillment'
      fullPath: '/fulfillment'
      preLoaderRoute: typeof ShellFulfillmentRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/inventory': {
      id: '/_shell/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof ShellInventoryRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/products': {
      id: '/_shell/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ShellProductsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/sellers': {
      id: '/_shell/sellers'
      path: '/sellers'
      fullPath: '/sellers'
      preLoaderRoute: typeof ShellSellersRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/users': {
      id: '/_shell/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof ShellUsersRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/orders/': {
      id: '/_shell/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof ShellOrdersIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/orders/$orderId': {
      id: '/_shell/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof ShellOrdersOrderIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/orders/new': {
      id: '/_shell/orders/new'
      path: '/orders/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof ShellOrdersNewRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/receiving/': {
      id: '/_shell/receiving/'
      path: '/receiving'
      fullPath: '/receiving/'
      preLoaderRoute: typeof ShellReceivingIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/receiving/$receiptId': {
      id: '/_shell/receiving/$receiptId'
      path: '/receiving/$receiptId'
      fullPath: '/receiving/$receiptId'
      preLoaderRoute: typeof ShellReceivingReceiptIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/receiving/new': {
      id: '/_shell/receiving/new'
      path: '/receiving/new'
      fullPath: '/receiving/new'
      preLoaderRoute: typeof ShellReceivingNewRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellAuditRoute: typeof ShellAuditRoute
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellFulfillmentRoute: typeof ShellFulfillmentRoute
  ShellInventoryRoute: typeof ShellInventoryRoute
  ShellProductsRoute: typeof ShellProductsRoute
  ShellSellersRoute: typeof ShellSellersRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellUsersRoute: typeof ShellUsersRoute
  ShellOrdersOrderIdRoute: typeof ShellOrdersOrderIdRoute
  ShellOrdersNewRoute: typeof ShellOrdersNewRoute
  ShellReceivingReceiptIdRoute: typeof ShellReceivingReceiptIdRoute
  ShellReceivingNewRoute: typeof ShellReceivingNewRoute
  ShellOrdersIndexRoute: typeof ShellOrdersIndexRoute
  ShellReceivingIndexRoute: typeof ShellReceivingIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAuditRoute: ShellAuditRoute,
  ShellDashboardRoute: ShellDashboardRoute,
  ShellFulfillmentRoute: ShellFulfillmentRoute,
  ShellInventoryRoute: ShellInventoryRoute,
  ShellProductsRoute: ShellProductsRoute,
  ShellSellersRoute: ShellSellersRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellUsersRoute: ShellUsersRoute,
  ShellOrdersOrderIdRoute: ShellOrdersOrderIdRoute,
  ShellOrdersNewRoute: ShellOrdersNewRoute,
  ShellReceivingReceiptIdRoute: ShellReceivingReceiptIdRoute,
  ShellReceivingNewRoute: ShellReceivingNewRoute,
  ShellOrdersIndexRoute: ShellOrdersIndexRoute,
  ShellReceivingIndexRoute: ShellReceivingIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
